### PR TITLE
implemented the unit test for adding a tie

### PR DESCRIPTION
**Pull request by onanna**

### CODE REVIEW

**Review by Ramakrishnan83 — APPROVED** [review]
Approved

**Comment by RichFromGalvanize** [comment]
Looks like your test is failing. Click on "details" on the right of either of the actions that failed to get the details. Looks annotation-based.

**Comment by onanna** [comment]
> Looks like your test is failing. Click on "details" on the right of either of the actions that failed to get the details. Looks annotation-based.

added the annotation to the wrong pr and branch took it out

**Review by mosdevly — CHANGES_REQUESTED** [review]
Looks like you just need to update your branch with the new changes on master and this will be ready to merge!

**Comment by onanna** [comment]
closing so we can merge 22 instead

**Pull request closed without merging**
