### PR TITLE
implemented unit test for service layer for createTie and added the specific controller to the controller unit test in webmvctest annotation

### PR DESCRIPTION
**Pull request by onanna**

### CODE REVIEW

**Comment by mosdevly** [comment]
Duplicated in #21 and #22

Make sure your team is updating existing PRs when youre just adding feedback from reviews. Don't create new ones with the same code.

**Comment by onanna** [comment]
reopening after 22 because it has new test case

**Comment by RichFromGalvanize** [comment]
You will need fix these merge conflicts with your code before we can consider this...and of course make sure its a small one test PR.

**Comment by onanna** [comment]
merge conflict resolved

**Review by psivakoti — APPROVED** [review]
Changes looks good.

**Review by mosdevly — APPROVED** [review]

**Pull request merged**
